In [24]:
import torch
import numpy as np

In [25]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [26]:
scalar.item()

7

In [27]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [28]:
random_tensor = torch.rand(size=(3,4))

In [29]:
random_tensor

tensor([[0.0914, 0.8994, 0.9936, 0.4703],
        [0.1049, 0.5137, 0.2674, 0.4990],
        [0.7447, 0.7213, 0.4414, 0.5550]])

In [30]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

questions

In [31]:
torch.manual_seed(7)

# Creating a random tensor with shape (1, 1, 1, 10)
tensor = torch.rand(1, 1, 1, 10)

# Removing all dimensions of size 1
tensor_squeezed = tensor.squeeze()

print("Original Tensor:", tensor)
print("Original Shape:", tensor.shape)
print("Squeezed Tensor:", tensor_squeezed)
print("Squeezed Shape:", tensor_squeezed.shape)


Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original Shape: torch.Size([1, 1, 1, 10])
Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed Shape: torch.Size([10])


In [32]:
# Creating a tensor of shape (3, 2, 4)
tensor = torch.randn(3, 2, 4)

# Permuting dimensions (0 <-> 1)
permuted_tensor = tensor.permute(1, 0, 2)

print("Original shape:", tensor.shape)
print("Permuted shape:", permuted_tensor.shape)


Original shape: torch.Size([3, 2, 4])
Permuted shape: torch.Size([2, 3, 4])


In [33]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing a single element
element = tensor[1, 2]  # Accessing element at row 1, column 2

# Slicing a row
row = tensor[1, :]  # Accessing the second row

# Slicing a column
column = tensor[:, 2]  # Accessing the third column

print("Single element:", element)
print("Row:", row)
print("Column:", column)


Single element: tensor(6)
Row: tensor([4, 5, 6])
Column: tensor([3, 6, 9])


In [38]:
tensor = torch.rand(7, 7)
print("Random Tensor:", tensor)


Random Tensor: tensor([[0.0914, 0.8994, 0.9936, 0.4703, 0.1049, 0.5137, 0.2674],
        [0.4990, 0.7447, 0.7213, 0.4414, 0.5550, 0.6361, 0.1081],
        [0.3305, 0.5196, 0.2147, 0.2816, 0.6679, 0.7878, 0.5070],
        [0.3055, 0.7738, 0.2259, 0.3826, 0.9717, 0.5921, 0.5352],
        [0.6686, 0.3781, 0.9278, 0.0922, 0.3625, 0.4136, 0.2943],
        [0.3762, 0.8099, 0.7743, 0.5278, 0.9356, 0.1470, 0.2019],
        [0.7259, 0.4731, 0.0444, 0.1539, 0.1956, 0.8861, 0.7264]])


In [39]:
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7).T  # Transposing to shape (7, 1)

result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication Result:", result)


Matrix Multiplication Result: tensor([[1.3633],
        [2.2300],
        [1.5501],
        [1.3476],
        [1.5483],
        [1.9873],
        [1.8573]])


In [40]:
# Check for GPU availability
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)

print("Tensor 1 on GPU:", tensor1)
print("Tensor 2 on GPU:", tensor2)


Tensor 1 on GPU: tensor([[0.4924, 0.0531, 0.6775],
        [0.9072, 0.1691, 0.3684]], device='cuda:0')
Tensor 2 on GPU: tensor([[0.5421, 0.2149, 0.0364],
        [0.7189, 0.0897, 0.3745]], device='cuda:0')


In [41]:
# Transposing tensor2 to match dimensions for multiplication
tensor2_T = tensor2.T
result_gpu = torch.matmul(tensor1, tensor2_T)

print("Matrix Multiplication Result on GPU:", result_gpu)


Matrix Multiplication Result on GPU: tensor([[0.3030, 0.6125],
        [0.5415, 0.8053]], device='cuda:0')


In [42]:
max_value = result_gpu.max().item()
min_value = result_gpu.min().item()

print("Maximum Value:", max_value)
print("Minimum Value:", min_value)


Maximum Value: 0.8053197264671326
Minimum Value: 0.3029695451259613


In [43]:
max_index = result_gpu.argmax().item()
min_index = result_gpu.argmin().item()

print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)


Index of Maximum Value: 3
Index of Minimum Value: 0


In [44]:
torch.manual_seed(7)

# Creating a random tensor with shape (1, 1, 1, 10)
tensor = torch.rand(1, 1, 1, 10)

# Removing all dimensions of size 1
tensor_squeezed = tensor.squeeze()

print("Original Tensor:", tensor)
print("Original Shape:", tensor.shape)
print("Squeezed Tensor:", tensor_squeezed)
print("Squeezed Shape:", tensor_squeezed.shape)


Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original Shape: torch.Size([1, 1, 1, 10])
Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed Shape: torch.Size([10])


In [45]:
import numpy as np
print(np.__version__)


2.2.1
